// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedisCaching.Data;

#nullable disable

namespace RedisCaching.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241115151741_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RedisCaching.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa099b76-e195-462c-a1f2-6597be3b94df"),
                            Category = "Fruits",
                            Name = "Product 1",
                            Price = 750,
                            Quantity = 174
                        },
                        new
                        {
                            Id = new Guid("fa3eb05d-9ab5-4370-a38d-37fd6ccc091a"),
                            Category = "Beverages",
                            Name = "Product 2",
                            Price = 242,
                            Quantity = 129
                        },
                        new
                        {
                            Id = new Guid("2a97bb3d-132e-4a64-9f1f-4f2214f0ce51"),
                            Category = "Beverages",
                            Name = "Product 3",
                            Price = 451,
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("f87d6ebd-046a-48f1-aac9-54e5b97435c1"),
                            Category = "Fruits",
                            Name = "Product 4",
                            Price = 687,
                            Quantity = 144
                        },
                        new
                        {
                            Id = new Guid("cc39e406-eaf2-4cda-912d-b88e31927489"),
                            Category = "Beverages",
                            Name = "Product 5",
                            Price = 308,
                            Quantity = 189
                        },
                        new
                        {
                            Id = new Guid("abde2021-26a9-47e6-bcce-c506a53e9227"),
                            Category = "Vegetables",
                            Name = "Product 6",
                            Price = 572,
                            Quantity = 106
                        },
                        new
                        {
                            Id = new Guid("8f38cee9-e6f4-4f6e-88ef-10dcb7bf8def"),
                            Category = "Vegetables",
                            Name = "Product 7",
                            Price = 878,
                            Quantity = 120
                        },
                        new
                        {
                            Id = new Guid("bb3f0772-9a01-4c55-9abc-ef6d4f4b7ad9"),
                            Category = "Fruits",
                            Name = "Product 8",
                            Price = 889,
                            Quantity = 195
                        },
                        new
                        {
                            Id = new Guid("229bc634-3981-49cb-ac71-b5bb2baf27c4"),
                            Category = "Vegetables",
                            Name = "Product 9",
                            Price = 207,
                            Quantity = 173
                        },
                        new
                        {
                            Id = new Guid("ffa32222-42d2-488e-b94b-086f993b3a5a"),
                            Category = "Beverages",
                            Name = "Product 10",
                            Price = 554,
                            Quantity = 140
                        },
                        new
                        {
                            Id = new Guid("1a79ffe8-1f38-4632-8feb-224fe35dbb4d"),
                            Category = "Fruits",
                            Name = "Product 11",
                            Price = 613,
                            Quantity = 71
                        },
                        new
                        {
                            Id = new Guid("3e0eabd7-4aae-4201-b4ee-9533045fa884"),
                            Category = "Vegetables",
                            Name = "Product 12",
                            Price = 549,
                            Quantity = 69
                        },
                        new
                        {
                            Id = new Guid("fd2e51b3-bca0-4ceb-ada5-a4545eeb33f4"),
                            Category = "Fruits",
                            Name = "Product 13",
                            Price = 495,
                            Quantity = 35
                        },
                        new
                        {
                            Id = new Guid("58db086f-274a-411b-b438-dc477be28d37"),
                            Category = "Vegetables",
                            Name = "Product 14",
                            Price = 915,
                            Quantity = 142
                        },
                        new
                        {
                            Id = new Guid("172deefd-612a-43b6-a403-fe5d257e801c"),
                            Category = "Fruits",
                            Name = "Product 15",
                            Price = 801,
                            Quantity = 28
                        },
                        new
                        {
                            Id = new Guid("dc9c9a21-31ce-4404-b0c8-fa6ad85d1371"),
                            Category = "Vegetables",
                            Name = "Product 16",
                            Price = 110,
                            Quantity = 38
                        },
                        new
                        {
                            Id = new Guid("52357935-1456-4673-9616-06637fe739ec"),
                            Category = "Beverages",
                            Name = "Product 17",
                            Price = 149,
                            Quantity = 27
                        },
                        new
                        {
                            Id = new Guid("8e7b0fac-9286-4437-acf8-3fb30137a11e"),
                            Category = "Fruits",
                            Name = "Product 18",
                            Price = 282,
                            Quantity = 101
                        },
                        new
                        {
                            Id = new Guid("53449cdc-7833-4542-a7df-edf0d6ab5ded"),
                            Category = "Beverages",
                            Name = "Product 19",
                            Price = 687,
                            Quantity = 141
                        },
                        new
                        {
                            Id = new Guid("fb36e2dc-f5e6-404f-bdfb-3a5546041d08"),
                            Category = "Beverages",
                            Name = "Product 20",
                            Price = 572,
                            Quantity = 112
                        },
                        new
                        {
                            Id = new Guid("862b2f69-6ab0-4e8b-9785-62fdba7cd06b"),
                            Category = "Beverages",
                            Name = "Product 21",
                            Price = 880,
                            Quantity = 55
                        },
                        new
                        {
                            Id = new Guid("958c8ab9-670e-48d7-8ac5-aa3bef145ca6"),
                            Category = "Vegetables",
                            Name = "Product 22",
                            Price = 871,
                            Quantity = 174
                        },
                        new
                        {
                            Id = new Guid("2ebddda5-431d-4471-989b-21da69f22312"),
                            Category = "Vegetables",
                            Name = "Product 23",
                            Price = 138,
                            Quantity = 74
                        },
                        new
                        {
                            Id = new Guid("1cb0ff98-37d0-426f-8c19-b907cc65b2a4"),
                            Category = "Beverages",
                            Name = "Product 24",
                            Price = 595,
                            Quantity = 186
                        },
                        new
                        {
                            Id = new Guid("aa7d7847-d85e-4f17-b989-a9e461eef093"),
                            Category = "Fruits",
                            Name = "Product 25",
                            Price = 863,
                            Quantity = 182
                        },
                        new
                        {
                            Id = new Guid("741e7756-498c-404f-9e69-c2bbb8a5a0a9"),
                            Category = "Fruits",
                            Name = "Product 26",
                            Price = 193,
                            Quantity = 109
                        },
                        new
                        {
                            Id = new Guid("63eeebab-0ac4-479e-94af-5e52b593a6b0"),
                            Category = "Vegetables",
                            Name = "Product 27",
                            Price = 443,
                            Quantity = 16
                        },
                        new
                        {
                            Id = new Guid("c14a0fb9-2472-4736-a637-c61cbb23a56d"),
                            Category = "Beverages",
                            Name = "Product 28",
                            Price = 173,
                            Quantity = 57
                        },
                        new
                        {
                            Id = new Guid("8d5a17ec-dd1c-47a0-8820-123e126d6021"),
                            Category = "Fruits",
                            Name = "Product 29",
                            Price = 793,
                            Quantity = 80
                        },
                        new
                        {
                            Id = new Guid("b62d79e3-784d-4682-b754-544225aee246"),
                            Category = "Beverages",
                            Name = "Product 30",
                            Price = 874,
                            Quantity = 39
                        },
                        new
                        {
                            Id = new Guid("d4e699d0-f274-43de-841b-0fc639c2c4c2"),
                            Category = "Vegetables",
                            Name = "Product 31",
                            Price = 518,
                            Quantity = 145
                        },
                        new
                        {
                            Id = new Guid("239a6181-a70a-4e3d-868d-4eb4eb4a20df"),
                            Category = "Fruits",
                            Name = "Product 32",
                            Price = 833,
                            Quantity = 97
                        },
                        new
                        {
                            Id = new Guid("516ec62e-e31d-4204-a22b-04be510e744f"),
                            Category = "Vegetables",
                            Name = "Product 33",
                            Price = 479,
                            Quantity = 14
                        },
                        new
                        {
                            Id = new Guid("5ef75012-5315-4f83-be4d-4155ef35f652"),
                            Category = "Fruits",
                            Name = "Product 34",
                            Price = 729,
                            Quantity = 140
                        },
                        new
                        {
                            Id = new Guid("6dbe6c77-5fbb-40c7-870d-3bacb14c7b7a"),
                            Category = "Fruits",
                            Name = "Product 35",
                            Price = 396,
                            Quantity = 32
                        },
                        new
                        {
                            Id = new Guid("d1dd501e-a1c4-4e65-9a92-9f84a64979c2"),
                            Category = "Beverages",
                            Name = "Product 36",
                            Price = 724,
                            Quantity = 121
                        },
                        new
                        {
                            Id = new Guid("de1adc37-1b3c-4c34-bb15-58b4e3f95a47"),
                            Category = "Vegetables",
                            Name = "Product 37",
                            Price = 481,
                            Quantity = 191
                        },
                        new
                        {
                            Id = new Guid("3380922c-c121-4d47-ac4a-a26ec778442b"),
                            Category = "Fruits",
                            Name = "Product 38",
                            Price = 909,
                            Quantity = 23
                        },
                        new
                        {
                            Id = new Guid("794dfc67-1c87-4bdf-8395-925f6f6452aa"),
                            Category = "Fruits",
                            Name = "Product 39",
                            Price = 976,
                            Quantity = 15
                        },
                        new
                        {
                            Id = new Guid("7165f63d-5350-41d3-9cfa-f5b519d044a1"),
                            Category = "Vegetables",
                            Name = "Product 40",
                            Price = 300,
                            Quantity = 95
                        },
                        new
                        {
                            Id = new Guid("dd799072-26ff-4fac-aab6-9e8eeef17611"),
                            Category = "Vegetables",
                            Name = "Product 41",
                            Price = 10,
                            Quantity = 80
                        },
                        new
                        {
                            Id = new Guid("13b59e9e-791b-4e3f-87d1-d0451320c634"),
                            Category = "Vegetables",
                            Name = "Product 42",
                            Price = 779,
                            Quantity = 54
                        },
                        new
                        {
                            Id = new Guid("6e00ca8e-e38d-4ea9-b9f3-c8c2ffe11b08"),
                            Category = "Fruits",
                            Name = "Product 43",
                            Price = 410,
                            Quantity = 121
                        },
                        new
                        {
                            Id = new Guid("4f8c333f-80d1-4b63-95e1-a114f3e323fa"),
                            Category = "Fruits",
                            Name = "Product 44",
                            Price = 401,
                            Quantity = 156
                        },
                        new
                        {
                            Id = new Guid("d300b3e6-6855-4d7a-92ed-eed6e419ede5"),
                            Category = "Beverages",
                            Name = "Product 45",
                            Price = 545,
                            Quantity = 31
                        },
                        new
                        {
                            Id = new Guid("4b30ba54-9b82-41be-b782-f90da1772ef0"),
                            Category = "Vegetables",
                            Name = "Product 46",
                            Price = 893,
                            Quantity = 82
                        },
                        new
                        {
                            Id = new Guid("afb125a3-bd1c-4256-92c7-31395999a828"),
                            Category = "Beverages",
                            Name = "Product 47",
                            Price = 394,
                            Quantity = 192
                        },
                        new
                        {
                            Id = new Guid("b76ca3c0-33aa-4af5-b5a3-e328c70b84e4"),
                            Category = "Fruits",
                            Name = "Product 48",
                            Price = 261,
                            Quantity = 100
                        },
                        new
                        {
                            Id = new Guid("00e657e3-6c41-48b4-9611-9ab09c701aae"),
                            Category = "Vegetables",
                            Name = "Product 49",
                            Price = 293,
                            Quantity = 105
                        },
                        new
                        {
                            Id = new Guid("55c36314-96db-4ad8-aee7-50a1e7acda48"),
                            Category = "Beverages",
                            Name = "Product 50",
                            Price = 13,
                            Quantity = 56
                        },
                        new
                        {
                            Id = new Guid("748dbd26-3d9c-41b2-b436-4f668a0c88c2"),
                            Category = "Beverages",
                            Name = "Product 51",
                            Price = 278,
                            Quantity = 71
                        },
                        new
                        {
                            Id = new Guid("8dcd527e-f6ad-4679-92ba-aef2d167e047"),
                            Category = "Beverages",
                            Name = "Product 52",
                            Price = 744,
                            Quantity = 187
                        },
                        new
                        {
                            Id = new Guid("e03aac4c-0277-4d1f-8e0d-65323064dd8f"),
                            Category = "Vegetables",
                            Name = "Product 53",
                            Price = 845,
                            Quantity = 180
                        },
                        new
                        {
                            Id = new Guid("691620a7-4444-4f0f-a894-5f4c651a067a"),
                            Category = "Vegetables",
                            Name = "Product 54",
                            Price = 170,
                            Quantity = 161
                        },
                        new
                        {
                            Id = new Guid("33eae510-f473-4053-930d-e8aa9516a243"),
                            Category = "Beverages",
                            Name = "Product 55",
                            Price = 226,
                            Quantity = 147
                        },
                        new
                        {
                            Id = new Guid("cf09104b-cd3d-4f55-8715-2e897fde2028"),
                            Category = "Vegetables",
                            Name = "Product 56",
                            Price = 286,
                            Quantity = 197
                        },
                        new
                        {
                            Id = new Guid("9de819fd-e6f6-465a-9499-86237ea70c7f"),
                            Category = "Vegetables",
                            Name = "Product 57",
                            Price = 393,
                            Quantity = 198
                        },
                        new
                        {
                            Id = new Guid("9e02bb8a-e42c-4195-9779-79f15e16c652"),
                            Category = "Vegetables",
                            Name = "Product 58",
                            Price = 483,
                            Quantity = 84
                        },
                        new
                        {
                            Id = new Guid("151f6a33-76ea-4b5b-b75d-3d3d6bdf8506"),
                            Category = "Beverages",
                            Name = "Product 59",
                            Price = 151,
                            Quantity = 94
                        },
                        new
                        {
                            Id = new Guid("17a8f217-7309-4918-ac48-5d666e752c80"),
                            Category = "Beverages",
                            Name = "Product 60",
                            Price = 739,
                            Quantity = 62
                        },
                        new
                        {
                            Id = new Guid("16eed478-ec3b-40fb-8ae6-5fedd0fb192c"),
                            Category = "Beverages",
                            Name = "Product 61",
                            Price = 476,
                            Quantity = 29
                        },
                        new
                        {
                            Id = new Guid("607dace7-2551-4b9c-859b-2b72f7d73148"),
                            Category = "Vegetables",
                            Name = "Product 62",
                            Price = 980,
                            Quantity = 100
                        },
                        new
                        {
                            Id = new Guid("f63f6707-e955-49cd-8f8d-28f9be5f21ce"),
                            Category = "Beverages",
                            Name = "Product 63",
                            Price = 646,
                            Quantity = 140
                        },
                        new
                        {
                            Id = new Guid("eb602a08-cea2-4083-be05-88eff2c536ff"),
                            Category = "Beverages",
                            Name = "Product 64",
                            Price = 631,
                            Quantity = 54
                        },
                        new
                        {
                            Id = new Guid("7926c578-87bd-45dc-a396-2691b21bb80e"),
                            Category = "Fruits",
                            Name = "Product 65",
                            Price = 755,
                            Quantity = 75
                        },
                        new
                        {
                            Id = new Guid("28ed9f67-13be-4b96-b66c-3ab73004af83"),
                            Category = "Vegetables",
                            Name = "Product 66",
                            Price = 631,
                            Quantity = 46
                        },
                        new
                        {
                            Id = new Guid("9654861f-8dda-4275-bdd2-361add852ab8"),
                            Category = "Fruits",
                            Name = "Product 67",
                            Price = 208,
                            Quantity = 157
                        },
                        new
                        {
                            Id = new Guid("9fc50679-302f-4f79-8bcc-ac76ff88844e"),
                            Category = "Vegetables",
                            Name = "Product 68",
                            Price = 595,
                            Quantity = 192
                        },
                        new
                        {
                            Id = new Guid("3c148cd0-7d4f-4149-abb2-78432953be2a"),
                            Category = "Beverages",
                            Name = "Product 69",
                            Price = 593,
                            Quantity = 70
                        },
                        new
                        {
                            Id = new Guid("203df8ab-0739-401a-ace5-4ced6718308c"),
                            Category = "Fruits",
                            Name = "Product 70",
                            Price = 732,
                            Quantity = 38
                        },
                        new
                        {
                            Id = new Guid("b7a2dae3-23b8-49a2-bd81-cd904c905678"),
                            Category = "Vegetables",
                            Name = "Product 71",
                            Price = 972,
                            Quantity = 169
                        },
                        new
                        {
                            Id = new Guid("773130a3-f3bf-431d-b6ce-436e213a564c"),
                            Category = "Fruits",
                            Name = "Product 72",
                            Price = 600,
                            Quantity = 16
                        },
                        new
                        {
                            Id = new Guid("1dbadd98-695a-483e-906a-37a4241aeaa7"),
                            Category = "Vegetables",
                            Name = "Product 73",
                            Price = 172,
                            Quantity = 151
                        },
                        new
                        {
                            Id = new Guid("f53876e5-7ab5-48b4-ba5a-35b470318345"),
                            Category = "Fruits",
                            Name = "Product 74",
                            Price = 329,
                            Quantity = 113
                        },
                        new
                        {
                            Id = new Guid("0161384d-379d-4945-8d46-335752e15a59"),
                            Category = "Beverages",
                            Name = "Product 75",
                            Price = 437,
                            Quantity = 154
                        },
                        new
                        {
                            Id = new Guid("c939bb0d-21f0-45df-bb07-189746021d20"),
                            Category = "Beverages",
                            Name = "Product 76",
                            Price = 12,
                            Quantity = 27
                        },
                        new
                        {
                            Id = new Guid("44731ebe-04b4-4a4d-ba2f-7c4431d1a97d"),
                            Category = "Fruits",
                            Name = "Product 77",
                            Price = 440,
                            Quantity = 34
                        },
                        new
                        {
                            Id = new Guid("6758b683-de7c-4b0a-afbf-b50fad6e2eea"),
                            Category = "Beverages",
                            Name = "Product 78",
                            Price = 844,
                            Quantity = 23
                        },
                        new
                        {
                            Id = new Guid("f1a8d97c-8a42-4947-8847-a25611d4a5fd"),
                            Category = "Fruits",
                            Name = "Product 79",
                            Price = 397,
                            Quantity = 150
                        },
                        new
                        {
                            Id = new Guid("1db9f0c7-69d2-409d-8438-ddb929675e21"),
                            Category = "Beverages",
                            Name = "Product 80",
                            Price = 556,
                            Quantity = 154
                        },
                        new
                        {
                            Id = new Guid("c77b8571-31f9-447d-96b8-707096ee5c53"),
                            Category = "Beverages",
                            Name = "Product 81",
                            Price = 111,
                            Quantity = 53
                        },
                        new
                        {
                            Id = new Guid("a7f96f0f-91e1-4ce2-b923-cea966f411df"),
                            Category = "Vegetables",
                            Name = "Product 82",
                            Price = 544,
                            Quantity = 148
                        },
                        new
                        {
                            Id = new Guid("74a50e98-1162-44a1-a88a-48a228f60412"),
                            Category = "Vegetables",
                            Name = "Product 83",
                            Price = 828,
                            Quantity = 158
                        },
                        new
                        {
                            Id = new Guid("65443c06-a7aa-4e8a-848e-d85e43c176e2"),
                            Category = "Beverages",
                            Name = "Product 84",
                            Price = 866,
                            Quantity = 160
                        },
                        new
                        {
                            Id = new Guid("bcc46c17-4ab6-403c-9fe3-840a674d4d70"),
                            Category = "Fruits",
                            Name = "Product 85",
                            Price = 851,
                            Quantity = 65
                        },
                        new
                        {
                            Id = new Guid("ec55632a-9358-43ba-b70e-90abb5c3184e"),
                            Category = "Fruits",
                            Name = "Product 86",
                            Price = 992,
                            Quantity = 192
                        },
                        new
                        {
                            Id = new Guid("3df9fc21-f003-45b7-a131-8de8713d99d0"),
                            Category = "Fruits",
                            Name = "Product 87",
                            Price = 684,
                            Quantity = 45
                        },
                        new
                        {
                            Id = new Guid("343ac576-f5a3-4e59-91d3-9c071768bc8f"),
                            Category = "Vegetables",
                            Name = "Product 88",
                            Price = 29,
                            Quantity = 110
                        },
                        new
                        {
                            Id = new Guid("6a19520e-5c86-4ebf-820e-8c0baa6c9fc9"),
                            Category = "Beverages",
                            Name = "Product 89",
                            Price = 993,
                            Quantity = 20
                        },
                        new
                        {
                            Id = new Guid("0e5deb03-7a8c-47e6-9bfc-7808ff134959"),
                            Category = "Fruits",
                            Name = "Product 90",
                            Price = 375,
                            Quantity = 43
                        },
                        new
                        {
                            Id = new Guid("38795188-04b9-4984-a7d2-c57d4261af0d"),
                            Category = "Beverages",
                            Name = "Product 91",
                            Price = 333,
                            Quantity = 169
                        },
                        new
                        {
                            Id = new Guid("8f90f953-7dad-4721-b23f-4e9d4675f139"),
                            Category = "Fruits",
                            Name = "Product 92",
                            Price = 838,
                            Quantity = 156
                        },
                        new
                        {
                            Id = new Guid("9590f2d1-989a-4c84-9ca5-683a1b81820d"),
                            Category = "Vegetables",
                            Name = "Product 93",
                            Price = 533,
                            Quantity = 110
                        },
                        new
                        {
                            Id = new Guid("2eec67be-d3cf-410f-a888-e4eb5369d517"),
                            Category = "Vegetables",
                            Name = "Product 94",
                            Price = 103,
                            Quantity = 156
                        },
                        new
                        {
                            Id = new Guid("38116ba5-9534-418e-8d41-c25a1a64ca4d"),
                            Category = "Beverages",
                            Name = "Product 95",
                            Price = 939,
                            Quantity = 101
                        },
                        new
                        {
                            Id = new Guid("13d2ad0d-e5ed-4b7d-9241-63f8b33ed81d"),
                            Category = "Beverages",
                            Name = "Product 96",
                            Price = 423,
                            Quantity = 178
                        },
                        new
                        {
                            Id = new Guid("66d2615d-0ad5-4ec5-b6a5-acd1c935e515"),
                            Category = "Beverages",
                            Name = "Product 97",
                            Price = 42,
                            Quantity = 185
                        },
                        new
                        {
                            Id = new Guid("3f9a48db-122f-4c89-8e8d-c49ecae5099f"),
                            Category = "Fruits",
                            Name = "Product 98",
                            Price = 931,
                            Quantity = 99
                        },
                        new
                        {
                            Id = new Guid("ffcc72ad-56fa-404e-a8fd-c1c9f2e3ad94"),
                            Category = "Beverages",
                            Name = "Product 99",
                            Price = 954,
                            Quantity = 191
                        },
                        new
                        {
                            Id = new Guid("da29b8a6-67fe-431a-a1b1-e44393a2da62"),
                            Category = "Beverages",
                            Name = "Product 100",
                            Price = 771,
                            Quantity = 147
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
